version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/wordpress/wp-content/plugins/contact-form-7-tether
permissions:
  - object: /var/www/wordpress/wp-content/plugins/contact-form-7-tether
    pattern: "**"
    owner: www-data
    group: www-data


